<a href="https://colab.research.google.com/github/JoaoGrignetMS/Banco-de-dAdos/blob/main/C%C3%B3pia_de_2ds_bd_criar_bd_MySQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PROJETO: CRIAÇÃO DE BANCO DE DADOS COM MYSQL

In [ ]:
# Instala o MySQL
!apt-get install -y mysql-server

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libaio1 libcgi-fast-perl libcgi-pm-perl libclone-perl libencode-locale-perl
  libfcgi-bin libfcgi-perl libfcgi0ldbl libhtml-parser-perl
  libhtml-tagset-perl libhtml-template-perl libhttp-date-perl
  libhttp-message-perl libio-html-perl liblwp-mediatypes-perl libmecab2
  libprotobuf-lite23 liburi-perl mecab-ipadic mecab-ipadic-utf8 mecab-utils
  mysql-client-8.0 mysql-client-core-8.0 mysql-server-8.0
  mysql-server-core-8.0
Suggested packages:
  libdata-dump-perl libipc-sharedcache-perl libbusiness-isbn-perl libwww-perl
  mailx tinyca
The following NEW packages will be installed:
  libaio1 libcgi-fast-perl libcgi-pm-perl libclone-perl libencode-locale-perl
  libfcgi-bin libfcgi-perl libfcgi0ldbl libhtml-parser-perl
  libhtml-tagset-perl libhtml-template-perl libhttp-date-perl
  libhttp-message-perl libio-html-perl liblwp-mediatypes-perl libmecab2
  libprotobuf-lite23 liburi-perl mecab-ipadic mecab-ipadic-utf8 mecab-utils
  mysql-client-8.0 mysql-client-core-8.0 mysql-server mysql-server-8.0
  mysql-server-core-8.0
0 upgraded, 26 newly installed, 0 to remove and 2 not upgraded.
Need to get 29.7 MB of archives.
After this operation, 243 MB of additional disk space will be used.
Err:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mysql-client-core-8.0 amd64 8.0.44-0ubuntu0.22.04.2
  404  Not Found [IP: 185.125.190.81 80]
Err:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mysql-client-8.0 amd64 8.0.44-0ubuntu0.22.04.2
  404  Not Found [IP: 185.125.190.81 80]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libaio1 amd64 0.3.112-13build1 [7,176 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libmecab2 amd64 0.996-14build9 [199 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libprotobuf-lite23 amd64 3.12.4-1ubuntu7.22.04.4 [209 kB]
Err:6 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mysql-server-core-8.0 amd64 8.0.44-0ubuntu0.22.04.2
  404  Not Found [IP: 185.125.190.81 80]
Err:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mysql-server-8.0 amd64 8.0.44-0ubuntu0.22.04.2
  404  Not Found [IP: 185.125.190.81 80]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libhtml-tagset-perl all 3.20-4 [12.5 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 liburi-perl all 5.10-1 [78.8 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libhtml-parser-perl amd64 3.76-1build2 [88.4 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcgi-pm-perl all 4.54-1 [188 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libfcgi0ldbl amd64 2.4.2-2ubuntu0.1 [28.1 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy/main amd64 libfcgi-perl amd64 0.82+ds-1build1 [22.8 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcgi-fast-perl all 1:2.15-1 [10.5 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 libclone-perl amd64 0.45-1build3 [11.0 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy/main amd64 libencode-locale-perl all 1.05-1.1 [11.8 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libfcgi-bin amd64 2.4.2-2ubuntu0.1 [11.1 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy/main amd64 libhtml-template-perl all 2.97-1.1 [59.1 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy/main amd64 libhttp-date-perl all 6.05-1 [9,920 B]
Get:20 http://archive.ubuntu.com/ubuntu jammy/main amd64 libio-html-perl all 1.004-2 [15.4 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy/main amd64 liblwp-mediatypes-perl all 6.04-1 [19.5 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy/main amd64 libhttp-message-perl all 6.36-1 [76.8 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy/main amd64 mecab-utils amd64 0.996-14build9 [4,850 B]
Get:24 http://archive.ubuntu.com/ubuntu jammy/main amd64 mecab-ipadic all 2.7.0-20070801+main-3 [6,718 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy/main amd64 mecab-ipadic-utf8 all 2.7.0-20070801+main-3 [4,384 B]
Err:26 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mysql-server all 8.0.44-0ubuntu0.22.04.2
  404  Not Found [IP: 185.125.190.81 80]
Fetched 7,786 kB in 0s (17.0 MB/s)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-8.0/mysql-client-core-8.0_8.0.44-0ubuntu0.22.04.2_amd64.deb  404  Not Found [IP: 185.125.190.81 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-8.0/mysql-client-8.0_8.0.44-0ubuntu0.22.04.2_amd64.deb  404  Not Found [IP: 185.125.190.81 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-8.0/mysql-server-core-8.0_8.0.44-0ubuntu0.22.04.2_amd64.deb  404  Not Found [IP: 185.125.190.81 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-8.0/mysql-server-8.0_8.0.44-0ubuntu0.22.04.2_amd64.deb  404  Not Found [IP: 185.125.190.81 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-8.0/mysql-server_8.0.44-0ubuntu0.22.04.2_all.deb  404  Not Found [IP: 185.125.190.81 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

In [ ]:
# Inicia o serviço do SGDB MySQL
!service mysql start

mysql: unrecognized service

In [ ]:
# Configura o MySQL e cria o banco de dados (execute só 1 vez, para executar de novo deve trocar nomes de banco e usuário)
!mysql -e "CREATE DATABASE Escola;" && echo "Banco de dados 'Escola' criado com sucesso."
!mysql -e "CREATE USER 'adm'@'localhost' IDENTIFIED BY 'senha';" && echo "Usuário 'adm' criado com sucesso."
!mysql -e "GRANT ALL PRIVILEGES ON Escola.* TO 'adm'@'localhost';" && echo "Privilégios concedidos ao usuário 'adm'."
!mysql -e "FLUSH PRIVILEGES;" && echo "Privilégios atualizados com sucesso."

/bin/bash: line 1: mysql: command not found
/bin/bash: line 1: mysql: command not found
/bin/bash: line 1: mysql: command not found
/bin/bash: line 1: mysql: command not found

In [ ]:
# Exlclui o banco de dados
#!mysql -e "DROP DATABASE Escola;" && echo "Banco de dados 'Escola' excluído com sucesso."

# Exlcui usuario do banco de dados
#!mysql -e "DROP USER 'name'@'localhost';" && echo "Usuário 'name' excluído com sucesso."

In [ ]:
# Instala a biblioteca mysql.connector
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.6.0-cp312-cp312-manylinux_2_28_x86_64.whl (34.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.5/34.5 MB 58.4 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.6.0

In [ ]:
# Importa biblioteca mysql.connector
import mysql.connector
from mysql.connector import Error

try:
    # Conecta ao banco de dados Escola
    conn = mysql.connector.connect(
        host="localhost",
        user="adm",
        password="senha",
        database="Escola"
    )
    # Imprime mensagens para confirmar a conexão
    if conn.is_connected():
        print("Conexão realizada com sucesso.")

    cursor = conn.cursor()

except Error as e:
    print(f"Erro ao conectar ao MySQL: {e}")

Erro ao conectar ao MySQL: 2003: Can't connect to MySQL server on 'localhost:3306' (Errno 111: Connection refused)

In [38]:
# Cria tabelas no bd Escola
cursor.execute("CREATE TABLE Alunos (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(100) NOT NULL, data_nascimento DATE NOT NULL, endereco VARCHAR(255) NOT NULL, serie INT NOT NULL);")
cursor.execute("CREATE TABLE Professores (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(100) NOT NULL, especialidade VARCHAR(100) NOT NULL, data_contratacao DATE NOT NULL);")
cursor.execute("CREATE TABLE Disciplinas (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(100) NOT NULL, carga_horaria INT NOT NULL);")

ProgrammingError: Cursor is not connected

In [20]:
# Exclui tabelas do banco de dados
#cursor.execute("DROP TABLE IF EXISTS Alunos1;")
#cursor.execute("DROP TABLE IF EXISTS Professores1;")
#cursor.execute("DROP TABLE IF EXISTS Disciplinas1;")

In [22]:
 # Exibe as tabelas criadas
 cursor.execute("SHOW TABLES;")
 tables = cursor.fetchall()
 print("Tabelas no banco de dados 'Escola:")
 for table in tables:
  print(table[0])

NameError: name 'cursor' is not defined

In [ ]:
# Apagar tabelas com "1" no nome
tabelas_para_apagar = ["Alunos1", "Disciplinas1", "Professores1"]
for tabela in tabelas_para_apagar:
  try:
    cursor.execute(f"DROP TABLE IF EXISTS {tabela};")
    print(f"Tabela '{tabela}' apagada com sucesso.")
  except Error as e:
    print(f"Erro ao apagar a tabela '{tabela}': {e}")

In [ ]:
# Insere dados nas tabelas
cursor.execute("INSERT INTO Alunos (nome, data_nascimento, endereco, serie) VALUES ('João Silva', '2005-05-15', 'Rua A, 123', 2), ('Maria Oliveira', '2006-08-22', 'Rua B, 456', 2);")
cursor.execute("INSERT INTO Professores (nome, especialidade, data_contratacao) VALUES ('Carlos Souza', 'Matemática', '2020-02-01'), ('Ana Lima', 'Português', '2019-03-15');")
cursor.execute("INSERT INTO Disciplinas (nome, carga_horaria) VALUES ('Matemática', 200), ('Português', 180);")

In [ ]:
# Importa biblioteca Pandas
import pandas as pd

# Função para exibir dados de uma tabela em formato de DataFrame
def exibir_tabela(nome_tabela):
  cursor.execute(f"SELECT * FROM {nome_tabela};")
  rows = cursor.fetchall()
  colunas = [desc[0] for desc in cursor.description]
  df = pd.DataFrame(rows, columns=colunas)
  print(f"\nDados da tabela {nome_tabela}:")
  display(df)

# Exibe tabelas criadas
cursor.execute("SHOW TABLES;")
tables = cursor.fetchall()
print("Tabelas no banco de dados 'Escola':")
for table in tables:
  print(table[0])
  exibir_tabela(table[0])

In [ ]:
# Consulta dados na tabela Alunos
cursor.execute("SELECT * FROM Alunos;")
for row in cursor.fetchall():
    print(row)

In [ ]:
# Consulta dados na tabela Professores
cursor.execute("SELECT * FROM Professores;")
for row in cursor.fetchall():
    # Formata a data como string (texto)
    id, nome, especialidade, data_contratacao = row
    print(f"ID: {id}, Nome: {nome}, Especialidade: {especialidade}, Data de Contratação: {data_contratacao.strftime('%Y-%m-%d')}")

In [ ]:
# Consulta dados na tabela Disciplinas
cursor.execute("SELECT * FROM Disciplinas;")
for row in cursor.fetchall():
    print(row)

In [ ]:
# Fecha a conexão com o SGDB MySQL
try:
    cursor.close()
    conn.close()
    print("Conexão fechada com sucesso.")
except Error as e:
    print(f"Erro ao fechar a conexão com MySQL: {e}")

# Task
Reinstall MySQL Server, configure it by creating the 'Escola' database and 'adm' user with 'senha' password, grant necessary privileges, install the `mysql-connector-python` library, connect to the database, create 'Alunos', 'Professores', and 'Disciplinas' tables, insert example data, display all table data to confirm, and finally close the database connection.

## Reinstalar e Configurar MySQL

### Subtask:
Atualizar a lista de pacotes e reinstalar o MySQL Server para resolver os erros '404 Not Found' que ocorreram durante a instalação inicial. Após a instalação, iniciar o serviço MySQL.

**Reasoning**:
The first step is to update the package list to ensure that the system has access to the latest package information, which might resolve the '404 Not Found' errors encountered during the initial MySQL installation.

In [23]:
import warnings
warnings.filterwarnings('ignore')

!apt-get update

Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:4 https://cli.github.com/packages stable InRelease [3,917 B]
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:8 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease [24.6 kB]
Get:9 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [85.2 kB]
Get:10 https://cli.github.com/packages stable/main amd64 Packages [357 B]
Get:11 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [6,861 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,613 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [70.9 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,107 kB]
Get:16 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [39.2 kB]
Get:17 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy/main amd64 Packages [75.3 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,767 kB]
Get:19 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,785 kB]
Get:20 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,302 kB]
Get:21 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [62.6 kB]
Get:22 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,626 kB]
Get:23 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,913 kB]
Fetched 37.7 MB in 3s (10.8 MB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

**Reasoning**:
After updating the package list, the next step is to reinstall MySQL Server using the `--fix-missing` flag to address potential issues with dependency downloads and then start the MySQL service to ensure it's running.

In [24]:
import warnings
warnings.filterwarnings('ignore')

# Reinstalls MySQL Server, ensuring all dependencies are correctly handled.
!apt-get install -y mysql-server --fix-missing

# Starts the MySQL service.
!service mysql start

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libaio1 libcgi-fast-perl libcgi-pm-perl libclone-perl libencode-locale-perl
  libfcgi-bin libfcgi-perl libfcgi0ldbl libhtml-parser-perl
  libhtml-tagset-perl libhtml-template-perl libhttp-date-perl
  libhttp-message-perl libio-html-perl liblwp-mediatypes-perl libmecab2
  libprotobuf-lite23 liburi-perl mecab-ipadic mecab-ipadic-utf8 mecab-utils
  mysql-client-8.0 mysql-client-core-8.0 mysql-server-8.0
  mysql-server-core-8.0
Suggested packages:
  libdata-dump-perl libipc-sharedcache-perl libbusiness-isbn-perl libwww-perl
  mailx tinyca
The following NEW packages will be installed:
  libaio1 libcgi-fast-perl libcgi-pm-perl libclone-perl libencode-locale-perl
  libfcgi-bin libfcgi-perl libfcgi0ldbl libhtml-parser-perl
  libhtml-tagset-perl libhtml-template-perl libhttp-date-perl
  libhttp-message-perl libio-html-perl liblwp-mediatypes-perl libmecab2
  libprotobuf-lite23 liburi-perl mecab-ipadic mecab-ipadic-utf8 mecab-utils
  mysql-client-8.0 mysql-client-core-8.0 mysql-server mysql-server-8.0
  mysql-server-core-8.0
0 upgraded, 26 newly installed, 0 to remove and 103 not upgraded.
Need to get 29.8 MB of archives.
After this operation, 243 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mysql-client-core-8.0 amd64 8.0.45-0ubuntu0.22.04.1 [2,707 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mysql-client-8.0 amd64 8.0.45-0ubuntu0.22.04.1 [22.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libaio1 amd64 0.3.112-13build1 [7,176 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libmecab2 amd64 0.996-14build9 [199 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libprotobuf-lite23 amd64 3.12.4-1ubuntu7.22.04.6 [209 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mysql-server-core-8.0 amd64 8.0.45-0ubuntu0.22.04.1 [17.8 MB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mysql-server-8.0 amd64 8.0.45-0ubuntu0.22.04.1 [1,448 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libhtml-tagset-perl all 3.20-4 [12.5 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 liburi-perl all 5.10-1 [78.8 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libhtml-parser-perl amd64 3.76-1build2 [88.4 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcgi-pm-perl all 4.54-1 [188 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libfcgi0ldbl amd64 2.4.2-2ubuntu0.1 [28.1 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy/main amd64 libfcgi-perl amd64 0.82+ds-1build1 [22.8 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcgi-fast-perl all 1:2.15-1 [10.5 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 libclone-perl amd64 0.45-1build3 [11.0 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy/main amd64 libencode-locale-perl all 1.05-1.1 [11.8 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libfcgi-bin amd64 2.4.2-2ubuntu0.1 [11.1 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy/main amd64 libhtml-template-perl all 2.97-1.1 [59.1 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy/main amd64 libhttp-date-perl all 6.05-1 [9,920 B]
Get:20 http://archive.ubuntu.com/ubuntu jammy/main amd64 libio-html-perl all 1.004-2 [15.4 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy/main amd64 liblwp-mediatypes-perl all 6.04-1 [19.5 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy/main amd64 libhttp-message-perl all 6.36-1 [76.8 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy/main amd64 mecab-utils amd64 0.996-14build9 [4,850 B]
Get:24 http://archive.ubuntu.com/ubuntu jammy/main amd64 mecab-ipadic all 2.7.0-20070801+main-3 [6,718 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy/main amd64 mecab-ipadic-utf8 all 2.7.0-20070801+main-3 [4,384 B]
Get:26 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mysql-server all 8.0.45-0ubuntu0.22.04.1 [9,462 B]
Fetched 29.8 MB in 1s (44.0 MB/s)
Preconfiguring packages ...
Selecting previously unselected package mysql-client-core-8.0.
(Reading database ... 117540 files and directories currently installed.)
Preparing to unpack .../00-mysql-client-core-8.0_8.0.45-0ubuntu0.22.04.1_amd64.deb ...
Unpacking mysql-client-core-8.0 (8.0.45-0ubuntu0.22.04.1) ...
Selecting previously unselected package mysql-client-8.0.
Preparing to unpack .../01-mysql-client-8.0_8.0.45-0ubuntu0.22.04.1_amd64.deb ...
Unpacking mysql-client-8.0 (8.0.45-0ubuntu0.22.04.1) ...
Selecting previously unselected package libaio1:amd64.
Preparing to unpack .../02-libaio1_0.3.112-13build1_amd64.deb ...
Unpacking libaio1:amd64 (0.3.112-13build1) ...
Selecting previously unselected package libmecab2:amd64.
Preparing to unpack .../03-libmecab2_0.996-14build9_amd64.deb ...
Unpacking libmecab2:amd64 (0.996-14build9) ...
Selecting previously unselected package libprotobuf-lite23:amd64.
Preparing to unpack .../04-libprotobuf-lite23_3.12.4-1ubuntu7.22.04.6_amd64.deb ...
Unpacking libprotobuf-lite23:amd64 (3.12.4-1ubuntu7.22.04.6) ...
Selecting previously unselected package mysql-server-core-8.0.
Preparing to unpack .../05-mysql-server-core-8.0_8.0.45-0ubuntu0.22.04.1_amd64.deb ...
Unpacking mysql-server-core-8.0 (8.0.45-0ubuntu0.22.04.1) ...
Selecting previously unselected package mysql-server-8.0.
Preparing to unpack .../06-mysql-server-8.0_8.0.45-0ubuntu0.22.04.1_amd64.deb ...
Unpacking mysql-server-8.0 (8.0.45-0ubuntu0.22.04.1) ...
Selecting previously unselected package libhtml-tagset-perl.
Preparing to unpack .../07-libhtml-tagset-perl_3.20-4_all.deb ...
Unpacking libhtml-tagset-perl (3.20-4) ...
Selecting previously unselected package liburi-perl.
Preparing to unpack .../08-liburi-perl_5.10-1_all.deb ...
Unpacking liburi-perl (5.10-1) ...
Selecting previously unselected package libhtml-parser-perl:amd64.
Preparing to unpack .../09-libhtml-parser-perl_3.76-1build2_amd64.deb ...
Unpacking libhtml-parser-perl:amd64 (3.76-1build2) ...
Selecting previously unselected package libcgi-pm-perl.
Preparing to unpack .../10-libcgi-pm-perl_4.54-1_all.deb ...
Unpacking libcgi-pm-perl (4.54-1) ...
Selecting previously unselected package libfcgi0ldbl:amd64.
Preparing to unpack .../11-libfcgi0ldbl_2.4.2-2ubuntu0.1_amd64.deb ...
Unpacking libfcgi0ldbl:amd64 (2.4.2-2ubuntu0.1) ...
Selecting previously unselected package libfcgi-perl:amd64.
Preparing to unpack .../12-libfcgi-perl_0.82+ds-1build1_amd64.deb ...
Unpacking libfcgi-perl:amd64 (0.82+ds-1build1) ...
Selecting previously unselected package libcgi-fast-perl.
Preparing to unpack .../13-libcgi-fast-perl_1%3a2.15-1_all.deb ...
Unpacking libcgi-fast-perl (1:2.15-1) ...
Selecting previously unselected package libclone-perl.
Preparing to unpack .../14-libclone-perl_0.45-1build3_amd64.deb ...
Unpacking libclone-perl (0.45-1build3) ...
Selecting previously unselected package libencode-locale-perl.
Preparing to unpack .../15-libencode-locale-perl_1.05-1.1_all.deb ...
Unpacking libencode-locale-perl (1.05-1.1) ...
Selecting previously unselected package libfcgi-bin.
Preparing to unpack .../16-libfcgi-bin_2.4.2-2ubuntu0.1_amd64.deb ...
Unpacking libfcgi-bin (2.4.2-2ubuntu0.1) ...
Selecting previously unselected package libhtml-template-perl.
Preparing to unpack .../17-libhtml-template-perl_2.97-1.1_all.deb ...
Unpacking libhtml-template-perl (2.97-1.1) ...
Selecting previously unselected package libhttp-date-perl.
Preparing to unpack .../18-libhttp-date-perl_6.05-1_all.deb ...
Unpacking libhttp-date-perl (6.05-1) ...
Selecting previously unselected package libio-html-perl.
Preparing to unpack .../19-libio-html-perl_1.004-2_all.deb ...
Unpacking libio-html-perl (1.004-2) ...
Selecting previously unselected package liblwp-mediatypes-perl.
Preparing to unpack .../20-liblwp-mediatypes-perl_6.04-1_all.deb ...
Unpacking liblwp-mediatypes-perl (6.04-1) ...
Selecting previously unselected package libhttp-message-perl.
Preparing to unpack .../21-libhttp-message-perl_6.36-1_all.deb ...
Unpacking libhttp-message-perl (6.36-1) ...
Selecting previously unselected package mecab-utils.
Preparing to unpack .../22-mecab-utils_0.996-14build9_amd64.deb ...
Unpacking mecab-utils (0.996-14build9) ...
Selecting previously unselected package mecab-ipadic.
Preparing to unpack .../23-mecab-ipadic_2.7.0-20070801+main-3_all.deb ...
Unpacking mecab-ipadic (2.7.0-20070801+main-3) ...
Selecting previously unselected package mecab-ipadic-utf8.
Preparing to unpack .../24-mecab-ipadic-utf8_2.7.0-20070801+main-3_all.deb ...
Unpacking mecab-ipadic-utf8 (2.7.0-20070801+main-3) ...
Selecting previously unselected package mysql-server.
Preparing to unpack .../25-mysql-server_8.0.45-0ubuntu0.22.04.1_all.deb ...
Unpacking mysql-server (8.0.45-0ubuntu0.22.04.1) ...
Setting up libhttp-date-perl (6.05-1) ...
Setting up libmecab2:amd64 (0.996-14build9) ...
Setting up mysql-client-core-8.0 (8.0.45-0ubuntu0.22.04.1) ...
Setting up libfcgi0ldbl:amd64 (2.4.2-2ubuntu0.1) ...
Setting up libclone-perl (0.45-1build3) ...
Setting up libhtml-tagset-perl (3.20-4) ...
Setting up liblwp-mediatypes-perl (6.04-1) ...
Setting up libfcgi-bin (2.4.2-2ubuntu0.1) ...
Setting up libencode-locale-perl (1.05-1.1) ...
Setting up libprotobuf-lite23:amd64 (3.12.4-1ubuntu7.22.04.6) ...
Setting up mecab-utils (0.996-14build9) ...
Setting up libio-html-perl (1.004-2) ...
Setting up mysql-client-8.0 (8.0.45-0ubuntu0.22.04.1) ...
Setting up libfcgi-perl:amd64 (0.82+ds-1build1) ...
Setting up libaio1:amd64 (0.3.112-13build1) ...
Setting up liburi-perl (5.10-1) ...
Setting up libhttp-message-perl (6.36-1) ...
Setting up mecab-ipadic (2.7.0-20070801+main-3) ...
Compiling IPA dictionary for Mecab.  This takes long time...
reading /usr/share/mecab/dic/ipadic/unk.def ... 40
emitting double-array: 100% |###########################################|
/usr/share/mecab/dic/ipadic/model.def is not found. skipped.
reading /usr/share/mecab/dic/ipadic/Prefix.csv ... 221
reading /usr/share/mecab/dic/ipadic/Noun.verbal.csv ... 12146
reading /usr/share/mecab/dic/ipadic/Filler.csv ... 19
reading /usr/share/mecab/dic/ipadic/Postp-col.csv ... 91
reading /usr/share/mecab/dic/ipadic/Noun.adjv.csv ... 3328
reading /usr/share/mecab/dic/ipadic/Others.csv ... 2
reading /usr/share/mecab/dic/ipadic/Suffix.csv ... 1393
reading /usr/share/mecab/dic/ipadic/Noun.demonst.csv ... 120
reading /usr/share/mecab/dic/ipadic/Noun.place.csv ... 72999
reading /usr/share/mecab/dic/ipadic/Noun.others.csv ... 151
reading /usr/share/mecab/dic/ipadic/Symbol.csv ... 208
reading /usr/share/mecab/dic/ipadic/Noun.name.csv ... 34202
reading /usr/share/mecab/dic/ipadic/Noun.nai.csv ... 42
reading /usr/share/mecab/dic/ipadic/Adnominal.csv ... 135
reading /usr/share/mecab/dic/ipadic/Verb.csv ... 130750
reading /usr/share/mecab/dic/ipadic/Postp.csv ... 146
reading /usr/share/mecab/dic/ipadic/Noun.proper.csv ... 27328
reading /usr/share/mecab/dic/ipadic/Adverb.csv ... 3032
reading /usr/share/mecab/dic/ipadic/Adj.csv ... 27210
reading /usr/share/mecab/dic/ipadic/Auxil.csv ... 199
reading /usr/share/mecab/dic/ipadic/Noun.csv ... 60477
reading /usr/share/mecab/dic/ipadic/Noun.number.csv ... 42
reading /usr/share/mecab/dic/ipadic/Noun.org.csv ... 16668
reading /usr/share/mecab/dic/ipadic/Conjunction.csv ... 171
reading /usr/share/mecab/dic/ipadic/Interjection.csv ... 252
reading /usr/share/mecab/dic/ipadic/Noun.adverbal.csv ... 795
emitting double-array: 100% |###########################################|
reading /usr/share/mecab/dic/ipadic/matrix.def ... 1316x1316
emitting matrix      : 100% |###########################################|

done!
update-alternatives: using /var/lib/mecab/dic/ipadic to provide /var/lib/mecab/dic/debian (mecab-dictionary) in auto mode
Setting up mysql-server-core-8.0 (8.0.45-0ubuntu0.22.04.1) ...
Setting up mecab-ipadic-utf8 (2.7.0-20070801+main-3) ...
Compiling IPA dictionary for Mecab.  This takes long time...
reading /usr/share/mecab/dic/ipadic/unk.def ... 40
emitting double-array: 100% |###########################################|
/usr/share/mecab/dic/ipadic/model.def is not found. skipped.
reading /usr/share/mecab/dic/ipadic/Prefix.csv ... 221
reading /usr/share/mecab/dic/ipadic/Noun.verbal.csv ... 12146
reading /usr/share/mecab/dic/ipadic/Filler.csv ... 19
reading /usr/share/mecab/dic/ipadic/Postp-col.csv ... 91
reading /usr/share/mecab/dic/ipadic/Noun.adjv.csv ... 3328
reading /usr/share/mecab/dic/ipadic/Others.csv ... 2
reading /usr/share/mecab/dic/ipadic/Suffix.csv ... 1393
reading /usr/share/mecab/dic/ipadic/Noun.demonst.csv ... 120
reading /usr/share/mecab/dic/ipadic/Noun.place.csv ... 72999
reading /usr/share/mecab/dic/ipadic/Noun.others.csv ... 151
reading /usr/share/mecab/dic/ipadic/Symbol.csv ... 208
reading /usr/share/mecab/dic/ipadic/Noun.name.csv ... 34202
reading /usr/share/mecab/dic/ipadic/Noun.nai.csv ... 42
reading /usr/share/mecab/dic/ipadic/Adnominal.csv ... 135
reading /usr/share/mecab/dic/ipadic/Verb.csv ... 130750
reading /usr/share/mecab/dic/ipadic/Postp.csv ... 146
reading /usr/share/mecab/dic/ipadic/Noun.proper.csv ... 27328
reading /usr/share/mecab/dic/ipadic/Adverb.csv ... 3032
reading /usr/share/mecab/dic/ipadic/Adj.csv ... 27210
reading /usr/share/mecab/dic/ipadic/Auxil.csv ... 199
reading /usr/share/mecab/dic/ipadic/Noun.csv ... 60477
reading /usr/share/mecab/dic/ipadic/Noun.number.csv ... 42
reading /usr/share/mecab/dic/ipadic/Noun.org.csv ... 16668
reading /usr/share/mecab/dic/ipadic/Conjunction.csv ... 171
reading /usr/share/mecab/dic/ipadic/Interjection.csv ... 252
reading /usr/share/mecab/dic/ipadic/Noun.adverbal.csv ... 795
emitting double-array: 100% |###########################################|
reading /usr/share/mecab/dic/ipadic/matrix.def ... 1316x1316
emitting matrix      : 100% |###########################################|

done!
update-alternatives: using /var/lib/mecab/dic/ipadic-utf8 to provide /var/lib/mecab/dic/debian (mecab-dictionary) in auto mode
Setting up libhtml-parser-perl:amd64 (3.76-1build2) ...
Setting up mysql-server-8.0 (8.0.45-0ubuntu0.22.04.1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of stop.
update-alternatives: using /etc/mysql/mysql.cnf to provide /etc/mysql/my.cnf (my.cnf) in auto mode
Renaming removed key_buffer and myisam-recover options (if present)
mysqld will log errors to /var/log/mysql/error.log
mysqld is running as pid 4611
Created symlink /etc/systemd/system/multi-user.target.wants/mysql.service → /lib/systemd/system/mysql.service.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up libcgi-pm-perl (4.54-1) ...
Setting up libhtml-template-perl (2.97-1.1) ...
Setting up mysql-server (8.0.45-0ubuntu0.22.04.1) ...
Setting up libcgi-fast-perl (1:2.15-1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.11) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

 * Starting MySQL database server mysqld
su: warning: cannot change directory to /nonexistent: No such file or directory
   ...done.

**Reasoning**:
Now that MySQL is reinstalled and the service is running, the next step is to configure the database. This involves creating the 'Escola' database, setting up a user 'adm' with the password 'senha', granting all necessary privileges to this user on the 'Escola' database, and finally flushing the privileges to apply the changes.

In [26]:
# Configura o MySQL e cria o banco de dados (execute só 1 vez, para executar de novo deve trocar nomes de banco e usuário)
!mysql -e "CREATE DATABASE Escola;" && echo "Banco de dados 'Escola' criado com sucesso."
!mysql -e "CREATE USER 'adm'@'localhost' IDENTIFIED BY 'senha';" && echo "Usuário 'adm' criado com sucesso."
!mysql -e "GRANT ALL PRIVILEGES ON Escola.* TO 'adm'@'localhost';" && echo "Privilégios concedidos ao usuário 'adm'."
!mysql -e "FLUSH PRIVILEGES;" && echo "Privilégios atualizados com sucesso."

Banco de dados 'Escola' criado com sucesso.
Usuário 'adm' criado com sucesso.
Privilégios concedidos ao usuário 'adm'.
Privilégios atualizados com sucesso.

**Reasoning**:
Now that the MySQL server is set up and configured, the next step is to install the `mysql-connector-python` library. This library is essential for Python applications to connect and interact with the MySQL database, which is a requirement for the subsequent steps of the task.

In [27]:
import warnings
warnings.filterwarnings('ignore')

# Instala a biblioteca mysql.connector
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.12/dist-packages (9.6.0)

**Reasoning**:
With the MySQL server configured and the `mysql-connector-python` library installed, the next step is to connect to the 'Escola' database using the 'adm' user and 'senha' password. This will verify that the database setup is correct and allow for subsequent operations like table creation and data insertion.

In [28]:
import mysql.connector
from mysql.connector import Error

try:
    # Conecta ao banco de dados Escola
    conn = mysql.connector.connect(
        host="localhost",
        user="adm",
        password="senha",
        database="Escola"
    )
    # Imprime mensagens para confirmar a conexão
    if conn.is_connected():
        print("Conexão realizada com sucesso.")

    cursor = conn.cursor()

except Error as e:
    print(f"Erro ao conectar ao MySQL: {e}")

Conexão realizada com sucesso.

**Reasoning**:
Now that the connection to the MySQL database has been established, the next step is to create the required tables: 'Alunos', 'Professores', and 'Disciplinas', as specified in the task. This prepares the database for data insertion.

In [29]:
# Cria tabelas no bd Escola
cursor.execute("CREATE TABLE Alunos (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(100) NOT NULL, data_nascimento DATE NOT NULL, endereco VARCHAR(255) NOT NULL, serie INT NOT NULL);")
cursor.execute("CREATE TABLE Professores (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(100) NOT NULL, especialidade VARCHAR(100) NOT NULL, data_contratacao DATE NOT NULL);")
cursor.execute("CREATE TABLE Disciplinas (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(100) NOT NULL, carga_horaria INT NOT NULL);")

**Reasoning**:
With the tables 'Alunos', 'Professores', and 'Disciplinas' created, the next step is to insert the example data provided in the task into these respective tables. This will populate the database with initial records.

In [30]:
cursor.execute("INSERT INTO Alunos (nome, data_nascimento, endereco, serie) VALUES ('João Silva', '2005-05-15', 'Rua A, 123', 2), ('Maria Oliveira', '2006-08-22', 'Rua B, 456', 2);")
cursor.execute("INSERT INTO Professores (nome, especialidade, data_contratacao) VALUES ('Carlos Souza', 'Matemática', '2020-02-01'), ('Ana Lima', 'Português', '2019-03-15');")
cursor.execute("INSERT INTO Disciplinas (nome, carga_horaria) VALUES ('Matemática', 200), ('Português', 180);")

**Reasoning**:
After inserting the data, it is important to verify that the data has been correctly stored in each table. The `exibir_tabela` function, already defined in the notebook, provides a clear way to display the contents of each table in a structured format (DataFrame), confirming the success of the insertion operation.

In [31]:
import pandas as pd

# Função para exibir dados de uma tabela em formato de DataFrame
def exibir_tabela(nome_tabela):
  cursor.execute(f"SELECT * FROM {nome_tabela};")
  rows = cursor.fetchall()
  colunas = [desc[0] for desc in cursor.description]
  df = pd.DataFrame(rows, columns=colunas)
  print(f"\nDados da tabela {nome_tabela}:")
  display(df)

# Exibe tabelas criadas
cursor.execute("SHOW TABLES;")
tables = cursor.fetchall()
print("Tabelas no banco de dados 'Escola':")
for table in tables:
  print(table[0])
  exibir_tabela(table[0])

Tabelas no banco de dados 'Escola':
Alunos

Dados da tabela Alunos:

   id            nome data_nascimento    endereco  serie
0   1      João Silva      2005-05-15  Rua A, 123      2
1   2  Maria Oliveira      2006-08-22  Rua B, 456      2

Disciplinas

Dados da tabela Disciplinas:

   id        nome  carga_horaria
0   1  Matemática            200
1   2   Português            180

Professores

Dados da tabela Professores:

   id          nome especialidade data_contratacao
0   1  Carlos Souza    Matemática       2020-02-01
1   2      Ana Lima     Português       2019-03-15

**Reasoning**:
All required tables have been created, data inserted, and verified. The final step is to close the database connection to release resources.

In [32]:
try:
    cursor.close()
    conn.close()
    print("Conexão fechada com sucesso.")
except Error as e:
    print(f"Erro ao fechar a conexão com MySQL: {e}")

Conexão fechada com sucesso.

## Final Task

### Subtask:
Confirmar que o ambiente MySQL foi configurado com sucesso, o banco de dados e as tabelas foram criados e os dados inseridos e consultados.

## Summary:

### Q&A
The MySQL environment was successfully configured, the 'Escola' database and its tables ('Alunos', 'Professores', 'Disciplinas') were created, and data was inserted and queried as confirmed by the data verification steps.

### Data Analysis Key Findings
*   MySQL Server was successfully reinstalled and its service started, resolving initial installation errors.
*   A new database named 'Escola' was created.
*   A user 'adm' was created with the password 'senha' and granted all necessary privileges on the 'Escola' database.
*   The `mysql-connector-python` library was successfully installed.
*   A Python script successfully established a connection to the 'Escola' database using the 'adm' user credentials.
*   Three tables \('Alunos', 'Professores', 'Disciplinas'\) were successfully created within the 'Escola' database.
*   Example data was successfully inserted into the 'Alunos', 'Professores', and 'Disciplinas' tables.
*   Data verification using Pandas DataFrames confirmed that all inserted data was correctly stored and accessible in each table.
*   The database connection was successfully closed upon completion of operations.

### Insights or Next Steps
*   The comprehensive setup of MySQL, including database, user, tables, and data, provides a robust foundation for developing educational applications or further data management tasks.
*   Consider implementing parameterized queries to prevent SQL injection vulnerabilities and enhance security for future data operations.